
sudo: required
services:
- docker
language: java
env:
  global:
  - REGISTRY_USER=rsosem
  - DOCKER_IMAGE=kuharskimojster/ratings:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: "jFiGB6ropFqQmY/pCl/N1X2YFD92wQZt8iVIAtmS0YzDTzCW5fK1oaFkGYBAMBX95fG15rEkG155kBdxd0D56jzBhKF6J5Zf039SHPcvMMUNlp4dnFFX63xxd8GHLbRLLDTKclO8EykvGQoWd5D966EqQft2acZHKIkU3VzoOOtrORB9UyKdGgEJvp7m1QSI6iYNaveVCCRwy88381eskOm3ZfwABVSC0XZwDb2o1qkYtG0ZuZS+7B+2g6BohRBIP89zNZJIV3CphdrN2azgSXt2K+ozez3oF67VFsGYeZPjrY/Z6+qkAhry3cbc/iNFRle9zX06kzzwEthSTFf6fi5HG8RpIg0bp5OCNOTYZjQPEsBmaxiMZ4lfWEmktGAP8cJdTbhxoLcwnH4XEoLbr9GHg0HiEu1Y4l835q1knMyVZ8LAzIjKLwgZhaUEToZRYMyPvWcnSQ395DOsyh3Yapb3Q22NDXB0p2+8zSfkKlvhzWxexDznf/EtEnip8q59ehdAcAG4vn34e3JePXa1xSO+xdFUqXEulczbU4nLbTLFCKak6eB1XjEP3Mm8n00w9xVB346WsagaUXoA8xSGP1vG+Nfx6vgmiJm/4rgWuZ2c5FtFyORDAcvHlQpCX6jvC2UksnCFiYfrGSmHRLDE68qAUtX8FgBF3q2C79Ba9iw="
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_script:
- docker images
after_success:
- echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
- docker push "$DOCKER_IMAGE"
